<a href="https://colab.research.google.com/github/michaeledge27/CSCI290/blob/main/notebooks/premierLeagueProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [38]:
url = "https://github.com/michaeledge27/CSCI290/raw/main/data/matches.csv"
df = pd.read_csv(url)
df.head()

Unnamed: 0        date           time            comp        round  day  \
0           0  2020-09-21  20:15 (21:15)  Premier League  Matchweek 2  Mon   
1           2  2020-09-27  16:30 (17:30)  Premier League  Matchweek 3  Sun   
2           4  2020-10-03  17:30 (18:30)  Premier League  Matchweek 4  Sat   
3           5  2020-10-17  17:30 (18:30)  Premier League  Matchweek 5  Sat   
4           7  2020-10-24  12:30 (13:30)  Premier League  Matchweek 6  Sat   

  venue result  gf  ga  ...  match report  notes  sh  sot  dist fk pk pkatt  \
0  Away      W   3   1  ...  Match Report    NaN  13    8  21.1  2  1     1   
1  Home      L   2   5  ...  Match Report    NaN  16    5  19.8  1  0     0   
2  Away      D   1   1  ...  Match Report    NaN  23    1  18.2  1  0     0   
3  Home      W   1   0  ...  Match Report    NaN  13    5  17.7  0  0     0   
4  Away      D   1   1  ...  Match Report    NaN  14    7  20.9  1  0     0   

  season             team  
0   2024  Manchester City  
1   2024  Manchester City  
2   2024  Manchester City  
3   2024  Manchester City  
4   2024  Manchester City  

[5 rows x 28 columns]

In [39]:

df['win'] = (df['result']=='W') * 1
df['win'].head()

0    1
1    0
2    0
3    1
4    0
Name: win, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
train_set, test_set = train_test_split(df, test_size = 0.2, shuffle = True)

In [42]:
def Attribute_selection_method(dataFrame, target, measure):
  features = dataFrame.columns[dataFrame.columns != target]
  # splittingMeasure = dataFrame.columns[df.columns[1] if df.columns[1] != target else df.columns[2]]
  if measure == 'entropy':
    # calculate max entropy
    for feature in features:
      entropiesList = []
      counts = np.bincount(feature) #change to props stuff
      countProb = counts/len(features)
      entropyValue = -np.sum(countProb * np.log2(countProb))
      entropiesList.append(entropyValue)
      return features[entropiesList.index(min(entropiesList))]


  elif measure == 'gini':
    # calculate max entropy
    for feature in features:
      giniList = []
      counts = np.bincount(feature)
      countProb = counts/len(features)
      giniValue = 1 - np.sum(np.square(countProb))
      giniList.append(giniValue)
      return features[giniList.index(max(giniList))]

  else:
    return None


In [43]:
target = "win"
attribute = "xga"

In [44]:
vals = df[attribute].unique()
vals

array([0.6, 2.9, 2.4, 0.9, 0.3, 0.5, 1.2, 0.7, 0.4, 0.8, 0.2, 0.1, 1. ,
       1.5, 1.7, 1.6, 2.2, 1.1, 2.5, 3.4, 2. , 1.3, 1.8, 1.4, 2.7, 2.3,
       3.5, 1.9, 2.1, 3.1, 2.6, 4.1, 3.6, 0. , 3.3, 3. , 3.2, 3.9, 2.8,
       4.7, 3.7, 4. , 3.8, 7. , 4.5, 4.2, 5.2, 4.4, 4.3, 5.9, 4.6])

In [45]:
props = df[df[attribute] == vals[8]][target].value_counts(normalize=True)
props

win
1    0.649425
0    0.350575
Name: proportion, dtype: float64

In [46]:
entropy = 0
for i in range(len(props)):
  entropy = entropy - props[i]*math.log2(props[i])
entropy

0.9345802754794623

In [47]:
entropy = 0
entropyLists = []
for val in vals:
  weight = (len(df[df[attribute] == val])) /(len(df))
  props = df[df[attribute] == val][target].value_counts(normalize=True)
  for p in range(len(props)):
    entropy = entropy - weight*(p*(np.log2)(p))
    entropyLists.append(entropy)
returnValue = vals[entropyLists.index(min(entropyLists))]
returnValue


<ipython-input-47-60b436c7c705>:7: RuntimeWarning: divide by zero encountered in log2
  entropy = entropy - weight*(p*(np.log2)(p))
<ipython-input-47-60b436c7c705>:7: RuntimeWarning: invalid value encountered in scalar multiply
  entropy = entropy - weight*(p*(np.log2)(p))


0.6

In [48]:
giniImpurity = 0
giniLists = []
for val in vals:
  weight = (len(df[df[attribute] == val])) /(len(df))
  props = df[df[attribute] == val][target].value_counts(normalize=True)
  for p in range(len(props)):
    gini = 1 - np.sum(np.square(p))
    giniLists.append(gini)
returnValue = vals[giniLists.index(max(giniLists))]
returnValue

0.6

In [49]:
entropy = 0
giniImpurity = 0
def attribute_selection_method2(df, attribute, measure):
  if measure == 'entropy':
    entropyLists = []
    for val in vals:
      weight = (len(df[df[attribute] == val])) /(len(df))
      props = df[df[attribute] == val][target].value_counts(normalize=True)
      for p in range(len(props)):
        entropy = entropy - weight*(p*(np.log2)(p))
        entropyLists.append(entropy)
  return vals[entropyLists.index(min(entropyLists))]

  if measure == 'gini':
    giniLists = []
  for val in vals:
    weight = (len(df[df[attribute] == val])) /(len(df))
    props = df[df[attribute] == val][target].value_counts(normalize=True)
    for p in range(len(props)):
      gini = 1 - np.sum(np.square(p))
      giniLists.append(gini)
  return vals[giniLists.index(max(giniLists))]






In [50]:
train_set.columns

Index(['Unnamed: 0', 'date', 'time', 'comp', 'round', 'day', 'venue', 'result',
       'gf', 'ga', 'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain',
       'formation', 'referee', 'match report', 'notes', 'sh', 'sot', 'dist',
       'fk', 'pk', 'pkatt', 'season', 'team', 'win'],
      dtype='object')

In [51]:
train_set = train_set[['round', 'venue', 'xga', 'poss', 'sot', 'fk', 'pk', 'win']]

In [52]:
test_set = test_set[['round', 'venue', 'xga', 'poss', 'sot', 'fk', 'pk', 'win']]

In [53]:
X_train = train_set[['round', 'venue', 'xga', 'poss', 'sot', 'fk', 'pk']]
y_train = train_set[['win']]

In [54]:
X_test = test_set[['round', 'venue', 'xga', 'poss', 'sot', 'fk', 'pk']]
y_test = test_set[['win']]

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score
from sklearn.tree import plot_tree

In [57]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3830 entries, 4079 to 310
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   round   3830 non-null   object 
 1   venue   3830 non-null   object 
 2   xga     3830 non-null   float64
 3   poss    3830 non-null   int64  
 4   sot     3830 non-null   int64  
 5   fk      3830 non-null   int64  
 6   pk      3830 non-null   int64  
dtypes: float64(1), int64(4), object(2)
memory usage: 239.4+ KB


In [58]:
num_attributes = X_train.select_dtypes(include = ['int64', 'float64']).columns
cat_attributes = X_train.select_dtypes(include = ['object']).columns

In [59]:
trf = [ ('num', StandardScaler(), num_attributes),
       ('cat', OneHotEncoder( handle_unknown='ignore'), cat_attributes) ]
col_transform = ColumnTransformer( transformers = trf )

In [60]:
pipeline = Pipeline( steps = [('pre', col_transform),
 ('clf', DecisionTreeClassifier(max_depth=4))])

In [61]:
cross_val_score( pipeline, X_train, y_train, cv=5, scoring='accuracy')

array([0.71148825, 0.7310705 , 0.73759791, 0.71801567, 0.73368146])

In [62]:
cross_val_score( pipeline, X_train, y_train, cv=5, scoring='f1')

array([0.62350937, 0.64359862, 0.6035503 , 0.58891013, 0.62637363])

In [63]:
model = pipeline.fit( X_train, y_train )
model

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['xga', 'poss', 'sot', 'fk', 'pk'], dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['round', 'venue'], dtype='object'))])),
                ('clf', DecisionTreeClassifier(max_depth=4))])

In [64]:
predictions = pipeline.predict( X_test )

In [65]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [66]:
cm = confusion_matrix( y_test, predictions )
cm

array([[507,  82],
       [156, 213]])

In [67]:
import sklearn.metrics as metrics

TypeError: missing a required argument: 'y_pred'